
services:
  host-proxy:
    image: nginx:latest
    networks:
      - bifrost-global
    volumes:
      - ./config/host-proxy.conf:/etc/nginx/templates/default.conf.template:ro # overwrite the default
      - ./host-proxy/entrypoint/01-get-gateway.envsh:/docker-entrypoint.d/01-get-gateway.envsh:ro
